// ✅ OTP Store Module for International Users
// This module handles storing OTP locally-generated by frontend for international users
// No changes to existing send-otp-rent or verify-otp-rent endpoints

const express = require('express');
const router = express.Router();
const UserLogin = require('../user/UserModel');

/**
 * ✅ ENDPOINT: POST /PPC/store-otp
 * Purpose: Store locally-generated OTP in database for international users
 * 
 * Flow:
 * 1. Frontend generates OTP locally (6 digits)
 * 2. Frontend calls this endpoint to store OTP in UserLogin collection
 * 3. Frontend sends OTP via WhatsApp
 * 4. Later, verify-otp-rent finds this stored OTP and verifies it
 * 
 * This way, international flow matches India flow where OTP is stored in DB
 */
router.post('/store-otp', async (req, res) => {
  const { phoneNumber, otp, countryCode, country, loginMode = 'app', version } = req.body;

  // ✅ Validation
  if (!phoneNumber || !otp || !countryCode || !country) {
    return res.status(400).json({ 
      error: 'Phone number, OTP, country code, and country are required',
      received: { phoneNumber, otp: otp ? '***' : null, countryCode, country }
    });
  }

  try {
    // ✅ Normalize phone number (extract only digits, keep last 10)
    const phoneDigits = phoneNumber.replace(/\D/g, '').slice(-10);

    console.log('📱 Store OTP Request:', {
      phoneDigits,
      country,
      countryCode,
      loginMode,
      otpLength: otp.length,
      timestamp: new Date().toISOString()
    });

    // ✅ Check if user is banned or deleted (prevent storage for blocked users)
    const blockedUser = await UserLogin.findOne({
      phone: phoneDigits,
      status: { $in: ['banned', 'deleted'] }
    }).sort({ loginDate: -1 });

    if (blockedUser) {
      if (blockedUser.status === 'banned') {
        return res.status(403).json({
          error: 'Account banned',
          bannedDate: blockedUser.bannedDate,
          bannedReason: blockedUser.bannedReason,
          staffName: blockedUser.staffName
        });
      }
      if (blockedUser.status === 'deleted') {
        return res.status(403).json({
          error: 'Account deleted',
          deletedDate: blockedUser.deletedDate
        });
      }
    }

    // ✅ Validate OTP format (should be 6 digits)
    if (!otp || otp.length !== 6 || isNaN(otp)) {
      return res.status(400).json({
        error: 'OTP must be exactly 6 digits',
        received: otp ? `${otp.length} chars` : 'missing'
      });
    }

    // ✅ Store OTP in UserLogin collection
    // This creates a new record or updates existing one
    const userLogin = await UserLogin.findOneAndUpdate(
      { phone: phoneDigits },
      {
        phone: phoneDigits,
        otp: otp,
        loginDate: new Date(), // Set fresh login date
        otpStatus: 'pending', // Mark as pending for verification
        countryCode: countryCode,
        country: country, // Store country info
        loginMode: loginMode,
        version: version || null,
        status: 'active' // Ensure user is active
      },
      {
        new: true, // Return updated document
        upsert: true, // Create if doesn't exist
        runValidators: false // Skip validators to allow flexibility
      }
    );

    console.log('✅ OTP Stored Successfully:', {
      phone: phoneDigits,
      country: country,
      otpStatus: userLogin.otpStatus,
      storedAt: userLogin.loginDate,
      expiresAt: new Date(userLogin.loginDate.getTime() + 5 * 60 * 1000) // 5 min expiry
    });

    // ✅ Return success response
    res.status(200).json({
      message: 'OTP stored successfully for verification',
      result: {
        phone: phoneDigits,
        country: country,
        countryCode: countryCode,
        otpStatus: 'pending',
        expiresIn: '5 minutes',
        storedAt: userLogin.loginDate,
        nextStep: 'Send this OTP via WhatsApp to user, then call verify-otp-rent'
      }
    });

  } catch (error) {
    console.error('❌ Store OTP Error:', {
      message: error.message,
      code: error.code,
      stack: error.stack
    });

    res.status(500).json({
      error: 'Failed to store OTP',
      details: error.message,
      code: error.code
    });
  }
});


/**
 * ✅ ENDPOINT: POST /PPC/store-otp-resend
 * Purpose: Store new OTP for resend functionality (same as store-otp but with logging)
 */
router.post('/store-otp-resend', async (req, res) => {
  const { phoneNumber, otp, countryCode, country, loginMode = 'app' } = req.body;

  if (!phoneNumber || !otp || !countryCode || !country) {
    return res.status(400).json({ error: 'All fields required: phoneNumber, otp, countryCode, country' });
  }

  try {
    const phoneDigits = phoneNumber.replace(/\D/g, '').slice(-10);

    console.log('🔄 Resend OTP Request:', {
      phoneDigits,
      country,
      timestamp: new Date().toISOString()
    });

    // ✅ Validate OTP format
    if (!otp || otp.length !== 6 || isNaN(otp)) {
      return res.status(400).json({ error: 'OTP must be exactly 6 digits' });
    }

    // ✅ Update with new OTP
    const userLogin = await UserLogin.findOneAndUpdate(
      { phone: phoneDigits },
      {
        otp: otp,
        loginDate: new Date(), // Reset timer with new date
        otpStatus: 'pending',
        countryCode: countryCode,
        country: country,
        loginMode: loginMode,
        status: 'active'
      },
      {
        new: true,
        upsert: true,
        runValidators: false
      }
    );

    console.log('✅ OTP Resend Stored:', {
      phone: phoneDigits,
      country: country,
      timestamp: userLogin.loginDate
    });

    res.status(200).json({
      message: 'OTP resent and stored successfully',
      result: {
        phone: phoneDigits,
        country: country,
        otpStatus: 'pending',
        expiresIn: '5 minutes',
        nextStep: 'Send OTP via WhatsApp'
      }
    });

  } catch (error) {
    console.error('❌ Resend OTP Error:', error.message);
    res.status(500).json({
      error: 'Failed to resend OTP',
      details: error.message
    });
  }
});


/**
 * ✅ ENDPOINT: GET /PPC/check-pending-otp/:phoneNumber
 * Purpose: Check if user has a pending OTP (for debugging)
 */
router.get('/check-pending-otp/:phoneNumber', async (req, res) => {
  try {
    const phoneDigits = req.params.phoneNumber.replace(/\D/g, '').slice(-10);

    const userLogin = await UserLogin.findOne({
      phone: phoneDigits,
      otpStatus: 'pending'
    }).sort({ loginDate: -1 });

    if (!userLogin) {
      return res.status(404).json({
        message: 'No pending OTP found',
        phone: phoneDigits
      });
    }

    const isExpired = new Date() - userLogin.loginDate > 5 * 60 * 1000;
    const timeRemaining = Math.max(0, 5 * 60 - Math.floor((new Date() - userLogin.loginDate) / 1000));

    res.status(200).json({
      message: 'Pending OTP found',
      phone: phoneDigits,
      country: userLogin.country,
      countryCode: userLogin.countryCode,
      otpStatus: userLogin.otpStatus,
      storedAt: userLogin.loginDate,
      isExpired: isExpired,
      timeRemaining: `${timeRemaining} seconds`,
      expiresAt: new Date(userLogin.loginDate.getTime() + 5 * 60 * 1000)
    });

  } catch (error) {
    res.status(500).json({
      error: 'Failed to check pending OTP',
      details: error.message
    });
  }
});


/**
 * ✅ ENDPOINT: POST /PPC/clear-otp/:phoneNumber
 * Purpose: Clear OTP for a phone number (admin/testing)
 */
router.post('/clear-otp/:phoneNumber', async (req, res) => {
  try {
    const phoneDigits = req.params.phoneNumber.replace(/\D/g, '').slice(-10);

    const result = await UserLogin.findOneAndUpdate(
      { phone: phoneDigits },
      {
        otp: null,
        otpStatus: 'verified' // Mark as verified to prevent new attempts
      },
      { new: true }
    );

    if (!result) {
      return res.status(404).json({ error: 'User not found' });
    }

    res.status(200).json({
      message: 'OTP cleared successfully',
      phone: phoneDigits,
      otpStatus: result.otpStatus
    });

  } catch (error) {
    res.status(500).json({
      error: 'Failed to clear OTP',
      details: error.message
    });
  }
});


module.exports = router;
