const mongoose = require("mongoose");

// All available routes/pages extracted from Dashboard.jsx
const ALL_PERMISSIONS = [
  { key: "loginreport", label: "Login Report", group: "Reports" },
  { key: "adminreport", label: "Admin Report", group: "Reports" },
  { key: "detail-daily-report", label: "Detail Daily Report", group: "Reports" },
  { key: "property-payment-daily-report", label: "Property Payment Daily Report", group: "Reports" },
  { key: "daily-usage", label: "Daily Usage", group: "Reports" },

  { key: "statistics", label: "Statistics", group: "Analytics" },
  { key: "carstatics", label: "Car Statics", group: "Analytics" },
  { key: "buyers-statics", label: "Buyers Statics", group: "Analytics" },
  { key: "usage-statics", label: "Usage Statics", group: "Analytics" },
  { key: "all-property-statics", label: "All Property Statics", group: "Analytics" },
  { key: "all-buyer-statics", label: "All Buyer Statics", group: "Analytics" },
  { key: "all-usage-statics", label: "All Usage Statics", group: "Analytics" },
  { key: "rentid-statics", label: "RentId Statics", group: "Analytics" },
  { key: "without-all-statics", label: "Without All Statics", group: "Analytics" },

  { key: "plan", label: "Add Plan", group: "Plans" },
  { key: "buyerplan", label: "Buyer Plan", group: "Plans" },
  { key: "apply-on-demand", label: "Apply On Demand", group: "Plans" },
  { key: "limits", label: "Limits", group: "Plans" },

  { key: "users", label: "User List", group: "Users" },
  { key: "user-rolls", label: "User Rolls", group: "Users" },
  { key: "user-log", label: "Users Log", group: "Users" },
  { key: "rolls", label: "Rolls", group: "Users" },
  { key: "office", label: "Office List", group: "Users" },
  { key: "my-account", label: "My Account", group: "Users" },
  { key: "profile", label: "Profile", group: "Users" },
  { key: "profile-table", label: "Profile Table", group: "Users" },
  { key: "all-user-datas", label: "All User Datas", group: "Users" },
  { key: "without-property-user", label: "Without Property User", group: "Users" },
  { key: "without-30-days-user", label: "Without 30 Days User", group: "Users" },
  { key: "login-direct-user", label: "Login Direct User", group: "Users" },
  { key: "logout-direct-user", label: "Logout Direct User", group: "Users" },
  { key: "login-user-datas", label: "Login User Datas", group: "Users" },
  { key: "separate-login-user", label: "Separate Login User", group: "Users" },
  { key: "remove-plan-phone", label: "Remove Plan Phone", group: "Users" },

  { key: "property-list", label: "Property List", group: "Properties" },
  { key: "add-car", label: "Add Property", group: "Properties" },
  { key: "all-car", label: "All Properties", group: "Properties" },
  { key: "approved-car", label: "Approved Properties", group: "Properties" },
  { key: "pending-car", label: "Pending Properties", group: "Properties" },
  { key: "paid-car", label: "Paid Properties", group: "Properties" },
  { key: "free-car", label: "Free Properties", group: "Properties" },
  { key: "expire-car", label: "Expire Properties", group: "Properties" },
  { key: "removed-car", label: "Removed Properties", group: "Properties" },
  { key: "reported-cars", label: "Reported Properties", group: "Properties" },
  { key: "preapproved-car", label: "Pre-Approved Properties", group: "Properties" },
  { key: "puc-car", label: "PUC Properties", group: "Properties" },
  { key: "deleted-properties", label: "Deleted Properties", group: "Properties" },
  { key: "developer-property", label: "Developer Property", group: "Properties" },
  { key: "feature-property", label: "Featured Properties", group: "Properties" },
  { key: "postby-property", label: "Posted By Property", group: "Properties" },
  { key: "promotor-property", label: "Promotor Property", group: "Properties" },
  { key: "friend-property", label: "Friend Property", group: "Properties" },
  { key: "tanent-property", label: "Tenant Property", group: "Properties" },
  { key: "get-all-property-datas", label: "All Property Status", group: "Properties" },
  { key: "py-properties", label: "PY Properties", group: "Properties" },
  { key: "edit-property", label: "Edit Property", group: "Properties" },
  { key: "set-property", label: "Set Property", group: "Properties" },
  { key: "detail", label: "Property Detail", group: "Properties" },
  { key: "exclusive-location", label: "Exclusive Location", group: "Properties" },

  { key: "buyers-assistant", label: "Buyers Assistant", group: "Buyers" },
  { key: "get-buyer-assistance", label: "Get Buyer Assistance", group: "Buyers" },
  { key: "add-buyer-assistance", label: "Add Buyer Assistance", group: "Buyers" },
  { key: "view-buyer-assistance", label: "View Buyer Assistance", group: "Buyers" },
  { key: "edit-buyer-assistance", label: "Edit Buyer Assistance", group: "Buyers" },
  { key: "active-buyer-assistant", label: "Active Buyer Assistant", group: "Buyers" },
  { key: "pending-assistant", label: "Pending Assistant", group: "Buyers" },
  { key: "expired-assistant", label: "Expired Assistant", group: "Buyers" },
  { key: "transfer-assistant", label: "Transfer Assistant", group: "Buyers" },
  { key: "buyerlist-interest", label: "Buyer List Interest", group: "Buyers" },
  { key: "buyers-list-interest-tried", label: "Buyer List Interest Tried", group: "Buyers" },
  { key: "buyers-contacted", label: "Buyers Contacted", group: "Buyers" },
  { key: "buyers-shortlisted", label: "Buyers Shortlisted", group: "Buyers" },
  { key: "get-all-buyerlist-viewed", label: "Buyer List Viewed", group: "Buyers" },
  { key: "matched-buyer", label: "Matched Buyer", group: "Buyers" },
  { key: "get-matched-properties", label: "Matched Properties", group: "Buyers" },

  { key: "bills-datas", label: "Bill Datas", group: "Billing" },
  { key: "create-bill", label: "Create Bill", group: "Billing" },
  { key: "all-bills", label: "All Bills", group: "Billing" },
  { key: "paid-bills", label: "Paid Bills", group: "Billing" },
  { key: "free-bills", label: "Free Bills", group: "Billing" },
  { key: "ba-free-bills", label: "BA Free Bills", group: "Billing" },
  { key: "ba-paid-bills", label: "BA Paid Bills", group: "Billing" },
  { key: "buyer-create-bill", label: "Create Buyer Bill", group: "Billing" },
  { key: "all-buyer-bills", label: "All Buyer Bills", group: "Billing" },

  { key: "payment-failed", label: "Payment Failed", group: "Payments" },
  { key: "payment-success", label: "Payment Success", group: "Payments" },
  { key: "payment-paynow", label: "Payment Pay Now", group: "Payments" },
  { key: "payment-paylater", label: "Payment Pay Later", group: "Payments" },
  { key: "payment-failed-buyer", label: "Buyer Payment Failed", group: "Payments" },
  { key: "payment-success-buyer", label: "Buyer Payment Success", group: "Payments" },
  { key: "payment-paynow-buyer", label: "Buyer Payment Pay Now", group: "Payments" },
  { key: "payment-paylater-buyer", label: "Buyer Payment Pay Later", group: "Payments" },
  { key: "pay-later", label: "Pay Later", group: "Payments" },
  { key: "pay-u-money", label: "PayU Money", group: "Payments" },
  { key: "paymenttype", label: "Payment Type", group: "Payments" },
  { key: "assist-pay-later", label: "Assist Pay Later", group: "Payments" },
  { key: "assist-payu-money", label: "Assist PayU Money", group: "Payments" },

  { key: "create-followup", label: "Create Follow Up", group: "FollowUps" },
  { key: "followup-list", label: "Follow Up List", group: "FollowUps" },
  { key: "create-followup-buyer", label: "Create Buyer Follow Up", group: "FollowUps" },
  { key: "followup-list-buyer", label: "Buyer Follow Up List", group: "FollowUps" },
  { key: "car-follow-ups", label: "Car Follow Ups", group: "FollowUps" },
  { key: "buyers-follow-ups", label: "Buyers Follow Ups", group: "FollowUps" },
  { key: "transfer-follow-ups", label: "Transfer Follow Ups", group: "FollowUps" },

  { key: "agent-car", label: "Agent Car", group: "Leads" },
  { key: "dealer-car", label: "Dealer Car", group: "Leads" },
  { key: "customer-car", label: "Customer Car", group: "Leads" },
  { key: "free-user-lead", label: "Free User Lead", group: "Leads" },
  { key: "new-car-lead", label: "New Car Lead", group: "Leads" },
  { key: "insurance-lead", label: "Insurance Lead", group: "Leads" },
  { key: "ba-loan-lead", label: "BA Loan Lead", group: "Leads" },
  { key: "help-loan-lead", label: "Help Loan Lead", group: "Leads" },
  { key: "mobile-view-lead", label: "Mobile View Lead", group: "Leads" },
  { key: "downloadleads", label: "Download Leads", group: "Leads" },
  { key: "callback-form", label: "Callback Form", group: "Leads" },

  { key: "city", label: "City", group: "Location" },
  { key: "area", label: "Area", group: "Location" },
  { key: "state", label: "State", group: "Location" },
  { key: "district", label: "District", group: "Location" },
  { key: "search-pincode", label: "Search Pincode", group: "Location" },
  { key: "fetch-all-address", label: "All Addresses", group: "Location" },
  { key: "get-all-address-request", label: "Address Requests", group: "Location" },

  { key: "admin-notification", label: "Admin Notification", group: "Communication" },
  { key: "notification-send", label: "Send Notification", group: "Communication" },
  { key: "bulk-whatsapp", label: "Bulk Whatsapp", group: "Communication" },
  { key: "single-send-whatsapp", label: "Single Send WhatsApp", group: "Communication" },
  { key: "contact-usage", label: "Contact Usage", group: "Communication" },
  { key: "contact-form-datas", label: "Contact Form Datas", group: "Communication" },
  { key: "set-property-message", label: "Set Property Message", group: "Communication" },

  { key: "car-make", label: "Car Make", group: "Settings" },
  { key: "car-model", label: "Car Model", group: "Settings" },
  { key: "puc-number", label: "PUC Number", group: "Settings" },
  { key: "puc-banner", label: "PUC Banner", group: "Settings" },
  { key: "tuc-banner", label: "TUC Banner", group: "Settings" },
  { key: "text-editor", label: "Text Editor", group: "Settings" },
  { key: "set-rentId", label: "Set PPC ID", group: "Settings" },
  { key: "adminlog", label: "Admin Log", group: "Settings" },
  { key: "help", label: "Help", group: "Settings" },

  { key: "upload-images-groom", label: "Upload Groom Images", group: "Media" },
  { key: "upload-images-bride", label: "Upload Bride Images", group: "Media" },
  { key: "upload-images-ads", label: "Upload Ads Images", group: "Media" },
  { key: "upload-images-ads-detail", label: "Upload Detail Ads", group: "Media" },
  { key: "photo-request", label: "Photo Request", group: "Media" },
  { key: "groom-click-datas", label: "Groom Click Datas", group: "Media" },
  { key: "bride-click-datas", label: "Bride Click Datas", group: "Media" },
];

const roleAccessSchema = new mongoose.Schema(
  {
    roleName: {
      type: String,
      required: [true, "Role name is required"],
      unique: true,
      trim: true,
    },
    description: {
      type: String,
      trim: true,
      default: "",
    },
    permissions: {
      type: [String], // array of permission keys
      default: [],
    },
    isActive: {
      type: Boolean,
      default: true,
    },
    createdBy: {
      type: String,
      default: "admin",
    },
  },
  { timestamps: true }
);

// Static helper to get all available permissions
roleAccessSchema.statics.getAllPermissions = function () {
  return ALL_PERMISSIONS;
};

const RoleAccess = mongoose.model("RoleAccess", roleAccessSchema);

module.exports = { RoleAccess, ALL_PERMISSIONS };
