// Chennai pincode reference data.
// Source: Chennai_Pincodes_Direction.xlsx (287 area rows, 4 directions).
// Update by re-running the extract script if the source spreadsheet changes.

export const CHENNAI_DIRECTIONS = ['Central', 'North', 'South', 'West'];

export const chennaiPincodeRows = [
  { area: 'Abhiramapuram', pincode: '600018', direction: 'Central' },
  { area: 'Alwarpet', pincode: '600018', direction: 'Central' },
  { area: 'Anna Salai', pincode: '600002', direction: 'Central' },
  { area: 'Anna Salai Extension', pincode: '600006', direction: 'Central' },
  { area: 'Boat Club Road', pincode: '600028', direction: 'Central' },
  { area: 'Broadway', pincode: '600001', direction: 'Central' },
  { area: 'Cathedral Road', pincode: '600086', direction: 'Central' },
  { area: 'Cenotaph 2nd Street', pincode: '600018', direction: 'Central' },
  { area: 'Cenotaph Road', pincode: '600018', direction: 'Central' },
  { area: 'Chamiers Road', pincode: '600028', direction: 'Central' },
  { area: 'Chepauk', pincode: '600005', direction: 'Central' },
  { area: 'Chetpet', pincode: '600031', direction: 'Central' },
  { area: 'Chintadripet', pincode: '600002', direction: 'Central' },
  { area: 'Dr Radhakrishnan Salai', pincode: '600004', direction: 'Central' },
  { area: 'Egmore', pincode: '600008', direction: 'Central' },
  { area: 'Egmore Museum Area', pincode: '600008', direction: 'Central' },
  { area: 'Elephant Gate', pincode: '600001', direction: 'Central' },
  { area: 'Esplanade', pincode: '600108', direction: 'Central' },
  { area: 'Flower Bazaar', pincode: '600001', direction: 'Central' },
  { area: 'Foreshore Estate', pincode: '600028', direction: 'Central' },
  { area: 'General Hospital', pincode: '600003', direction: 'Central' },
  { area: 'George Town', pincode: '600001', direction: 'Central' },
  { area: 'Gopalapuram', pincode: '600086', direction: 'Central' },
  { area: 'Greams Road', pincode: '600006', direction: 'Central' },
  { area: 'Haddows Road', pincode: '600006', direction: 'Central' },
  { area: 'Halls Road', pincode: '600008', direction: 'Central' },
  { area: 'Harrington Road', pincode: '600031', direction: 'Central' },
  { area: 'Kalmandapam', pincode: '600003', direction: 'Central' },
  { area: 'Kasturi Rangan Road', pincode: '600018', direction: 'Central' },
  { area: 'Kellys', pincode: '600010', direction: 'Central' },
  { area: 'Kilpauk', pincode: '600010', direction: 'Central' },
  { area: 'Kotwal Chavadi', pincode: '600003', direction: 'Central' },
  { area: 'Kutchery Road', pincode: '600004', direction: 'Central' },
  { area: 'Luz', pincode: '600004', direction: 'Central' },
  { area: 'Mannady', pincode: '600001', direction: 'Central' },
  { area: 'Mint', pincode: '600001', direction: 'Central' },
  { area: 'Moore Market', pincode: '600003', direction: 'Central' },
  { area: 'Mylapore', pincode: '600004', direction: 'Central' },
  { area: 'Nungambakkam', pincode: '600034', direction: 'Central' },
  { area: 'Nungambakkam High Road', pincode: '600034', direction: 'Central' },
  { area: 'Otteri', pincode: '600012', direction: 'Central' },
  { area: 'Park Town', pincode: '600003', direction: 'Central' },
  { area: 'Parrys', pincode: '600001', direction: 'Central' },
  { area: 'Pattalam', pincode: '600012', direction: 'Central' },
  { area: 'Periamet', pincode: '600003', direction: 'Central' },
  { area: "Peter's Road", pincode: '600086', direction: 'Central' },
  { area: 'Poes Garden', pincode: '600086', direction: 'Central' },
  { area: 'Poonamallee High Road', pincode: '600010', direction: 'Central' },
  { area: 'Pudupet', pincode: '600002', direction: 'Central' },
  { area: 'Pudur Agraharam', pincode: '600010', direction: 'Central' },
  { area: 'Purasawalkam', pincode: '600007', direction: 'Central' },
  { area: 'Rayala Towers Area', pincode: '600002', direction: 'Central' },
  { area: 'Royapettah', pincode: '600014', direction: 'Central' },
  { area: 'Rukmani Lakshmipathi Road', pincode: '600008', direction: 'Central' },
  { area: 'Rutland Gate', pincode: '600006', direction: 'Central' },
  { area: 'Sowcarpet', pincode: '600079', direction: 'Central' },
  { area: 'Spencer Plaza Area', pincode: '600002', direction: 'Central' },
  { area: 'Spur Tank Road', pincode: '600031', direction: 'Central' },
  { area: 'Sterling Road', pincode: '600034', direction: 'Central' },
  { area: 'Teynampet', pincode: '600018', direction: 'Central' },
  { area: 'Thousand Lights', pincode: '600006', direction: 'Central' },
  { area: 'Triplicane', pincode: '600005', direction: 'Central' },
  { area: 'Vepery', pincode: '600007', direction: 'Central' },
  { area: 'Wallace Garden', pincode: '600006', direction: 'Central' },
  { area: 'Alamathi', pincode: '600052', direction: 'North' },
  { area: 'Ambattur', pincode: '600053', direction: 'North' },
  { area: 'Ambattur Housing Board', pincode: '600053', direction: 'North' },
  { area: 'Ambattur Industrial Estate', pincode: '600058', direction: 'North' },
  { area: 'Ambattur OT', pincode: '600053', direction: 'North' },
  { area: 'Annanur', pincode: '600063', direction: 'North' },
  { area: 'Athipet', pincode: '600058', direction: 'North' },
  { area: 'Avadi', pincode: '600054', direction: 'North' },
  { area: 'Avadi Camp', pincode: '600054', direction: 'North' },
  { area: 'Ayyapakkam', pincode: '600077', direction: 'North' },
  { area: 'Basin Bridge', pincode: '600012', direction: 'North' },
  { area: 'Ennore', pincode: '600057', direction: 'North' },
  { area: 'Ennore Port', pincode: '600057', direction: 'North' },
  { area: 'Ernavur', pincode: '600057', direction: 'North' },
  { area: 'Erukkancheri', pincode: '600118', direction: 'North' },
  { area: 'Erukkancheri Extension', pincode: '600118', direction: 'North' },
  { area: 'Gummidipoondi', pincode: '601201', direction: 'North' },
  { area: 'Kaladipet', pincode: '600019', direction: 'North' },
  { area: 'Kamarajar Nagar', pincode: '600019', direction: 'North' },
  { area: 'Kathivakkam', pincode: '600057', direction: 'North' },
  { area: 'Kattupakkam', pincode: '600056', direction: 'North' },
  { area: 'Kodungaiyur', pincode: '600118', direction: 'North' },
  { area: 'Kolathur', pincode: '600099', direction: 'North' },
  { area: 'Kolathur Bus Depot Area', pincode: '600099', direction: 'North' },
  { area: 'Kolathur Extension', pincode: '600099', direction: 'North' },
  { area: 'Korattur', pincode: '600080', direction: 'North' },
  { area: 'Madhavaram', pincode: '600060', direction: 'North' },
  { area: 'Madhavaram Milk Colony', pincode: '600051', direction: 'North' },
  { area: 'Manali', pincode: '600068', direction: 'North' },
  { area: 'Manali New Town', pincode: '600103', direction: 'North' },
  { area: 'Mathur', pincode: '600068', direction: 'North' },
  { area: 'Minjur', pincode: '601203', direction: 'North' },
  { area: 'Moolakadai', pincode: '600118', direction: 'North' },
  { area: 'Narasingapuram', pincode: '600011', direction: 'North' },
  { area: 'Nerumbur', pincode: '600077', direction: 'North' },
  { area: 'Noombal', pincode: '600077', direction: 'North' },
  { area: 'Padi', pincode: '600050', direction: 'North' },
  { area: 'Padi Industrial Estate', pincode: '600050', direction: 'North' },
  { area: 'Padiyanallur', pincode: '600052', direction: 'North' },
  { area: 'Pattabiram', pincode: '600072', direction: 'North' },
  { area: 'Pazaverkadu', pincode: '601201', direction: 'North' },
  { area: 'Perambur', pincode: '600011', direction: 'North' },
  { area: 'Periyar Nagar', pincode: '600082', direction: 'North' },
  { area: 'Perumbur Barracks', pincode: '600011', direction: 'North' },
  { area: 'Ponneri', pincode: '601204', direction: 'North' },
  { area: 'Puzhal', pincode: '600066', direction: 'North' },
  { area: 'Puzhal New Colony', pincode: '600066', direction: 'North' },
  { area: 'Redhills', pincode: '600052', direction: 'North' },
  { area: 'Royapuram', pincode: '600013', direction: 'North' },
  { area: 'Sathyamurthy Nagar', pincode: '600019', direction: 'North' },
  { area: 'Sembiam', pincode: '600011', direction: 'North' },
  { area: 'Sholavaram', pincode: '600067', direction: 'North' },
  { area: 'Srinivasa Nagar Kolathur', pincode: '600099', direction: 'North' },
  { area: 'Surapet', pincode: '600066', direction: 'North' },
  { area: 'Thirumullaivoyal', pincode: '600062', direction: 'North' },
  { area: 'Thiruninravur', pincode: '600077', direction: 'North' },
  { area: 'Thiruvalangadu', pincode: '602001', direction: 'North' },
  { area: 'Thiruvotriyur Theradi', pincode: '600019', direction: 'North' },
  { area: 'Tiruverkadu', pincode: '600077', direction: 'North' },
  { area: 'Tiruvottiyur', pincode: '600019', direction: 'North' },
  { area: 'Tondiarpet', pincode: '600081', direction: 'North' },
  { area: 'Vallalar Nagar', pincode: '600081', direction: 'North' },
  { area: 'Vallur', pincode: '600120', direction: 'North' },
  { area: 'Vichoor', pincode: '600067', direction: 'North' },
  { area: 'Villivakkam', pincode: '600049', direction: 'North' },
  { area: 'Vyasarpadi', pincode: '600039', direction: 'North' },
  { area: 'Washermanpet', pincode: '600021', direction: 'North' },
  { area: 'Wimco Nagar', pincode: '600081', direction: 'North' },
  { area: 'Wimco Nagar Extension', pincode: '600081', direction: 'North' },
  { area: 'Adyar', pincode: '600020', direction: 'South' },
  { area: 'Akkarai', pincode: '600119', direction: 'South' },
  { area: 'Alandur', pincode: '600016', direction: 'South' },
  { area: 'Besant Nagar', pincode: '600090', direction: 'South' },
  { area: 'Chengalpattu', pincode: '603001', direction: 'South' },
  { area: 'Chitlapakkam', pincode: '600064', direction: 'South' },
  { area: 'Chromepet Extension', pincode: '600044', direction: 'South' },
  { area: 'Cowl Bazaar', pincode: '600001', direction: 'South' },
  { area: 'Ekkattuthangal', pincode: '600032', direction: 'South' },
  { area: 'Elcot SEZ Sholinganallur', pincode: '600119', direction: 'South' },
  { area: 'Guindy', pincode: '600032', direction: 'South' },
  { area: 'Injambakkam', pincode: '600115', direction: 'South' },
  { area: 'Jalladampet', pincode: '600097', direction: 'South' },
  { area: 'Kalpakkam', pincode: '603102', direction: 'South' },
  { area: 'Kancheepuram', pincode: '631501', direction: 'South' },
  { area: 'Kannagi Nagar', pincode: '600096', direction: 'South' },
  { area: 'Karanai', pincode: '603103', direction: 'South' },
  { area: 'Karapakkam', pincode: '600097', direction: 'South' },
  { area: 'Kazhipattur', pincode: '603103', direction: 'South' },
  { area: 'Keezhkattalai', pincode: '600117', direction: 'South' },
  { area: 'Kelambakkam', pincode: '603103', direction: 'South' },
  { area: 'Kodambakkam', pincode: '600024', direction: 'South' },
  { area: 'Kottivakkam', pincode: '600041', direction: 'South' },
  { area: 'Kotturpuram', pincode: '600085', direction: 'South' },
  { area: 'Kovalam', pincode: '603112', direction: 'South' },
  { area: 'Kovilambakkam', pincode: '600117', direction: 'South' },
  { area: 'Madambakkam', pincode: '600126', direction: 'South' },
  { area: 'Madipakkam', pincode: '600091', direction: 'South' },
  { area: 'Mahabalipuram', pincode: '603104', direction: 'South' },
  { area: 'Mahindra City', pincode: '603002', direction: 'South' },
  { area: 'Mambalam', pincode: '600033', direction: 'South' },
  { area: 'Maraimalai Nagar', pincode: '603209', direction: 'South' },
  { area: 'Medavakkam', pincode: '600100', direction: 'South' },
  { area: 'Mettukuppam', pincode: '600097', direction: 'South' },
  { area: 'Muthapudupet', pincode: '600119', direction: 'South' },
  { area: 'Nandambakkam', pincode: '600089', direction: 'South' },
  { area: 'Nandivaram-Guduvanchery', pincode: '603202', direction: 'South' },
  { area: 'Nanganallur', pincode: '600061', direction: 'South' },
  { area: 'Nanganallur Extension', pincode: '600061', direction: 'South' },
  { area: 'Nanmangalam', pincode: '600129', direction: 'South' },
  { area: 'Navalur', pincode: '600130', direction: 'South' },
  { area: 'Neelankarai', pincode: '600041', direction: 'South' },
  { area: 'North Usman Road', pincode: '600017', direction: 'South' },
  { area: 'Old Mahabalipuram Road Zone', pincode: '600096', direction: 'South' },
  { area: 'Ottiyambakkam', pincode: '603103', direction: 'South' },
  { area: 'Padur', pincode: '603103', direction: 'South' },
  { area: 'Palavakkam', pincode: '600041', direction: 'South' },
  { area: 'Pallikaranai', pincode: '600100', direction: 'South' },
  { area: 'Perumbakkam', pincode: '600100', direction: 'South' },
  { area: 'Perungudi', pincode: '600096', direction: 'South' },
  { area: 'Perungudi Industrial Estate', pincode: '600096', direction: 'South' },
  { area: 'Pondy Bazaar', pincode: '600017', direction: 'South' },
  { area: 'Potheri', pincode: '603203', direction: 'South' },
  { area: 'Puzhuthivakkam', pincode: '600091', direction: 'South' },
  { area: 'SIPCOT IT Park', pincode: '600130', direction: 'South' },
  { area: 'Saidapet', pincode: '600015', direction: 'South' },
  { area: 'Selaiyur', pincode: '600073', direction: 'South' },
  { area: 'Sembakkam', pincode: '600073', direction: 'South' },
  { area: 'Semmancheri', pincode: '600119', direction: 'South' },
  { area: 'Sholinganallur', pincode: '600119', direction: 'South' },
  { area: 'Singaperumalkoil', pincode: '603204', direction: 'South' },
  { area: 'Siruseri', pincode: '600130', direction: 'South' },
  { area: 'T.Nagar', pincode: '600017', direction: 'South' },
  { area: 'Tagore Nagar', pincode: '600117', direction: 'South' },
  { area: 'Tambaram West', pincode: '600045', direction: 'South' },
  { area: 'Thalambur', pincode: '600130', direction: 'South' },
  { area: 'Thiruporur', pincode: '603110', direction: 'South' },
  { area: 'Thiruvanmiyur', pincode: '600041', direction: 'South' },
  { area: 'Thoraipakkam', pincode: '600097', direction: 'South' },
  { area: 'Ullagaram', pincode: '600091', direction: 'South' },
  { area: 'Usman Road', pincode: '600017', direction: 'South' },
  { area: 'Velachery', pincode: '600042', direction: 'South' },
  { area: 'Vengaivasal', pincode: '600073', direction: 'South' },
  { area: 'West Mambalam', pincode: '600033', direction: 'South' },
  { area: 'Zamin Pallavaram', pincode: '600117', direction: 'South' },
  { area: 'Alandur Extension', pincode: '600016', direction: 'West' },
  { area: 'Alapakkam', pincode: '600116', direction: 'West' },
  { area: 'Alwarthirunagar', pincode: '600087', direction: 'West' },
  { area: 'Ambattur SIDCO', pincode: '600098', direction: 'West' },
  { area: 'Anakaputhur', pincode: '600070', direction: 'West' },
  { area: 'Anna Nagar', pincode: '600040', direction: 'West' },
  { area: 'Anna Nagar 2nd Avenue', pincode: '600040', direction: 'West' },
  { area: 'Anna Nagar East', pincode: '600102', direction: 'West' },
  { area: 'Anna Nagar Extension', pincode: '600101', direction: 'West' },
  { area: 'Anna Nagar West', pincode: '600101', direction: 'West' },
  { area: 'Arcot Road Zone', pincode: '600092', direction: 'West' },
  { area: 'Ariyalur', pincode: '600123', direction: 'West' },
  { area: 'Ariyalur Panchayat', pincode: '600123', direction: 'West' },
  { area: 'Arumbakkam', pincode: '600106', direction: 'West' },
  { area: 'Ashok Nagar', pincode: '600083', direction: 'West' },
  { area: 'Chembarambakkam', pincode: '600123', direction: 'West' },
  { area: 'Chromepet', pincode: '600044', direction: 'West' },
  { area: 'Guduvanchery', pincode: '603202', direction: 'West' },
  { area: 'Iyyappanthangal', pincode: '600056', direction: 'West' },
  { area: 'K.K. Nagar', pincode: '600078', direction: 'West' },
  { area: 'Kolapakkam', pincode: '600128', direction: 'West' },
  { area: 'Kovur', pincode: '600128', direction: 'West' },
  { area: 'Koyambedu', pincode: '600107', direction: 'West' },
  { area: 'Kundrathur', pincode: '600069', direction: 'West' },
  { area: 'Kuthambakkam', pincode: '602108', direction: 'West' },
  { area: 'Maduravoyal', pincode: '600095', direction: 'West' },
  { area: 'Manapakkam', pincode: '600125', direction: 'West' },
  { area: 'Mangadu', pincode: '600122', direction: 'West' },
  { area: 'Manimangalam', pincode: '601301', direction: 'West' },
  { area: 'Mappedu', pincode: '602105', direction: 'West' },
  { area: 'Mappedu Junction', pincode: '602105', direction: 'West' },
  { area: 'Mel Ayanambakkam', pincode: '600095', direction: 'West' },
  { area: 'Mevalurkuppam', pincode: '602105', direction: 'West' },
  { area: 'Mogappair', pincode: '600037', direction: 'West' },
  { area: 'Mogappair East', pincode: '600037', direction: 'West' },
  { area: 'Mogappair West', pincode: '600058', direction: 'West' },
  { area: 'Mudichur', pincode: '600048', direction: 'West' },
  { area: 'Mugalivakkam', pincode: '600125', direction: 'West' },
  { area: 'Nazarathpet', pincode: '602123', direction: 'West' },
  { area: 'Nerkundram', pincode: '600107', direction: 'West' },
  { area: 'Nesapakkam', pincode: '600092', direction: 'West' },
  { area: 'Nolambur', pincode: '600095', direction: 'West' },
  { area: 'Oragadam', pincode: '602105', direction: 'West' },
  { area: 'Pallavaram', pincode: '600043', direction: 'West' },
  { area: 'Pammal', pincode: '600075', direction: 'West' },
  { area: 'Paruthipattu', pincode: '600071', direction: 'West' },
  { area: 'Pattabiram North', pincode: '600072', direction: 'West' },
  { area: 'Peerkankaranai', pincode: '600063', direction: 'West' },
  { area: 'Pennalur', pincode: '602105', direction: 'West' },
  { area: 'Perambakkam', pincode: '601101', direction: 'West' },
  { area: 'Perungalathur', pincode: '600063', direction: 'West' },
  { area: 'Poonamallee', pincode: '600056', direction: 'West' },
  { area: 'Porur', pincode: '600116', direction: 'West' },
  { area: 'Pothiravakkam', pincode: '600110', direction: 'West' },
  { area: 'Radha Nagar', pincode: '600083', direction: 'West' },
  { area: 'Ramapuram', pincode: '600089', direction: 'West' },
  { area: 'Saligramam', pincode: '600093', direction: 'West' },
  { area: 'Senneerkuppam', pincode: '600056', direction: 'West' },
  { area: 'Shanthi Colony', pincode: '600040', direction: 'West' },
  { area: 'Sriperumbudur', pincode: '602105', direction: 'West' },
  { area: 'St Thomas Mount', pincode: '600016', direction: 'West' },
  { area: 'Tambaram', pincode: '600045', direction: 'West' },
  { area: 'Tambaram East', pincode: '600059', direction: 'West' },
  { area: 'Tambaram Sanatorium', pincode: '600047', direction: 'West' },
  { area: 'Thirumangalam', pincode: '600101', direction: 'West' },
  { area: 'Thirumazhisai', pincode: '600124', direction: 'West' },
  { area: 'Thirumazhisai Extension', pincode: '600124', direction: 'West' },
  { area: 'Thiruvallur', pincode: '602001', direction: 'West' },
  { area: 'Tiruttani', pincode: '631209', direction: 'West' },
  { area: 'Urapakkam', pincode: '603210', direction: 'West' },
  { area: 'Vadapalani', pincode: '600026', direction: 'West' },
  { area: 'Valasaravakkam', pincode: '600087', direction: 'West' },
  { area: 'Vallam', pincode: '631151', direction: 'West' },
  { area: 'Valsaravakkam', pincode: '600087', direction: 'West' },
  { area: 'Vanagaram', pincode: '600095', direction: 'West' },
  { area: 'Vandalur', pincode: '600048', direction: 'West' },
  { area: 'Veppampattu', pincode: '602024', direction: 'West' },
  { area: 'Virugambakkam', pincode: '600092', direction: 'West' },
  { area: 'Virugambakkam Extension', pincode: '600092', direction: 'West' },
];
