// Complete list of all ~250 countries with phone codes and ISO 3166-1 alpha-2 codes
export const countryCodes = [
  { code: '+93', country: 'Afghanistan', flag: 'AF' },
  { code: '+358', country: 'Åland Islands', flag: 'AX' },
  { code: '+355', country: 'Albania', flag: 'AL' },
  { code: '+213', country: 'Algeria', flag: 'DZ' },
  { code: '+1684', country: 'American Samoa', flag: 'AS' },
  { code: '+376', country: 'Andorra', flag: 'AD' },
  { code: '+244', country: 'Angola', flag: 'AO' },
  { code: '+1264', country: 'Anguilla', flag: 'AI' },
  { code: '+1268', country: 'Antigua and Barbuda', flag: 'AG' },
  { code: '+54', country: 'Argentina', flag: 'AR' },
  { code: '+374', country: 'Armenia', flag: 'AM' },
  { code: '+297', country: 'Aruba', flag: 'AW' },
  { code: '+61', country: 'Australia', flag: 'AU' },
  { code: '+43', country: 'Austria', flag: 'AT' },
  { code: '+994', country: 'Azerbaijan', flag: 'AZ' },
  { code: '+1242', country: 'Bahamas', flag: 'BS' },
  { code: '+973', country: 'Bahrain', flag: 'BH' },
  { code: '+880', country: 'Bangladesh', flag: 'BD' },
  { code: '+1246', country: 'Barbados', flag: 'BB' },
  { code: '+375', country: 'Belarus', flag: 'BY' },
  { code: '+32', country: 'Belgium', flag: 'BE' },
  { code: '+501', country: 'Belize', flag: 'BZ' },
  { code: '+229', country: 'Benin', flag: 'BJ' },
  { code: '+1441', country: 'Bermuda', flag: 'BM' },
  { code: '+975', country: 'Bhutan', flag: 'BT' },
  { code: '+591', country: 'Bolivia', flag: 'BO' },
  { code: '+387', country: 'Bosnia and Herzegovina', flag: 'BA' },
  { code: '+267', country: 'Botswana', flag: 'BW' },
  { code: '+55', country: 'Brazil', flag: 'BR' },
  { code: '+246', country: 'British Indian Ocean Territory', flag: 'IO' },
  { code: '+1284', country: 'British Virgin Islands', flag: 'VG' },
  { code: '+673', country: 'Brunei', flag: 'BN' },
  { code: '+359', country: 'Bulgaria', flag: 'BG' },
  { code: '+226', country: 'Burkina Faso', flag: 'BF' },
  { code: '+257', country: 'Burundi', flag: 'BI' },
  { code: '+855', country: 'Cambodia', flag: 'KH' },
  { code: '+237', country: 'Cameroon', flag: 'CM' },
  { code: '+1', country: 'Canada', flag: 'CA' },
  { code: '+238', country: 'Cape Verde', flag: 'CV' },
  { code: '+1345', country: 'Cayman Islands', flag: 'KY' },
  { code: '+236', country: 'Central African Republic', flag: 'CF' },
  { code: '+235', country: 'Chad', flag: 'TD' },
  { code: '+56', country: 'Chile', flag: 'CL' },
  { code: '+86', country: 'China', flag: 'CN' },
  { code: '+886', country: 'Taiwan', flag: 'TW' },
  { code: '+57', country: 'Colombia', flag: 'CO' },
  { code: '+269', country: 'Comoros', flag: 'KM' },
  { code: '+242', country: 'Congo', flag: 'CG' },
  { code: '+243', country: 'Democratic Republic of the Congo', flag: 'CD' },
  { code: '+506', country: 'Costa Rica', flag: 'CR' },
  { code: '+385', country: 'Croatia', flag: 'HR' },
  { code: '+53', country: 'Cuba', flag: 'CU' },
  { code: '+357', country: 'Cyprus', flag: 'CY' },
  { code: '+420', country: 'Czech Republic', flag: 'CZ' },
  { code: '+45', country: 'Denmark', flag: 'DK' },
  { code: '+253', country: 'Djibouti', flag: 'DJ' },
  { code: '+1767', country: 'Dominica', flag: 'DM' },
  { code: '+1', country: 'Dominican Republic', flag: 'DO' },
  { code: '+593', country: 'Ecuador', flag: 'EC' },
  { code: '+20', country: 'Egypt', flag: 'EG' },
  { code: '+503', country: 'El Salvador', flag: 'SV' },
  { code: '+240', country: 'Equatorial Guinea', flag: 'GQ' },
  { code: '+291', country: 'Eritrea', flag: 'ER' },
  { code: '+372', country: 'Estonia', flag: 'EE' },
  { code: '+251', country: 'Ethiopia', flag: 'ET' },
  { code: '+500', country: 'Falkland Islands', flag: 'FK' },
  { code: '+298', country: 'Faroe Islands', flag: 'FO' },
  { code: '+679', country: 'Fiji', flag: 'FJ' },
  { code: '+358', country: 'Finland', flag: 'FI' },
  { code: '+33', country: 'France', flag: 'FR' },
  { code: '+594', country: 'French Guiana', flag: 'GF' },
  { code: '+689', country: 'French Polynesia', flag: 'PF' },
  { code: '+508', country: 'Saint Pierre and Miquelon', flag: 'PM' },
  { code: '+241', country: 'Gabon', flag: 'GA' },
  { code: '+220', country: 'Gambia', flag: 'GM' },
  { code: '+995', country: 'Georgia', flag: 'GE' },
  { code: '+49', country: 'Germany', flag: 'DE' },
  { code: '+233', country: 'Ghana', flag: 'GH' },
  { code: '+350', country: 'Gibraltar', flag: 'GI' },
  { code: '+30', country: 'Greece', flag: 'GR' },
  { code: '+299', country: 'Greenland', flag: 'GL' },
  { code: '+1473', country: 'Grenada', flag: 'GD' },
  { code: '+590', country: 'Guadeloupe', flag: 'GP' },
  { code: '+1671', country: 'Guam', flag: 'GU' },
  { code: '+502', country: 'Guatemala', flag: 'GT' },
  { code: '+44', country: 'Guernsey', flag: 'GG' },
  { code: '+224', country: 'Guinea', flag: 'GN' },
  { code: '+245', country: 'Guinea-Bissau', flag: 'GW' },
  { code: '+592', country: 'Guyana', flag: 'GY' },
  { code: '+509', country: 'Haiti', flag: 'HT' },
  { code: '+504', country: 'Honduras', flag: 'HN' },
  { code: '+852', country: 'Hong Kong', flag: 'HK' },
  { code: '+36', country: 'Hungary', flag: 'HU' },
  { code: '+354', country: 'Iceland', flag: 'IS' },
  { code: '+91', country: 'India', flag: 'IN' },
  { code: '+62', country: 'Indonesia', flag: 'ID' },
  { code: '+98', country: 'Iran', flag: 'IR' },
  { code: '+964', country: 'Iraq', flag: 'IQ' },
  { code: '+353', country: 'Ireland', flag: 'IE' },
  { code: '+44', country: 'Isle of Man', flag: 'IM' },
  { code: '+972', country: 'Israel', flag: 'IL' },
  { code: '+39', country: 'Italy', flag: 'IT' },
  { code: '+225', country: 'Ivory Coast', flag: 'CI' },
  { code: '+1876', country: 'Jamaica', flag: 'JM' },
  { code: '+81', country: 'Japan', flag: 'JP' },
  { code: '+44', country: 'Jersey', flag: 'JE' },
  { code: '+962', country: 'Jordan', flag: 'JO' },
  { code: '+7', country: 'Kazakhstan', flag: 'KZ' },
  { code: '+254', country: 'Kenya', flag: 'KE' },
  { code: '+686', country: 'Kiribati', flag: 'KI' },
  { code: '+850', country: 'North Korea', flag: 'KP' },
  { code: '+82', country: 'South Korea', flag: 'KR' },
  { code: '+965', country: 'Kuwait', flag: 'KW' },
  { code: '+996', country: 'Kyrgyzstan', flag: 'KG' },
  { code: '+856', country: 'Laos', flag: 'LA' },
  { code: '+371', country: 'Latvia', flag: 'LV' },
  { code: '+961', country: 'Lebanon', flag: 'LB' },
  { code: '+266', country: 'Lesotho', flag: 'LS' },
  { code: '+231', country: 'Liberia', flag: 'LR' },
  { code: '+218', country: 'Libya', flag: 'LY' },
  { code: '+423', country: 'Liechtenstein', flag: 'LI' },
  { code: '+370', country: 'Lithuania', flag: 'LT' },
  { code: '+352', country: 'Luxembourg', flag: 'LU' },
  { code: '+853', country: 'Macao', flag: 'MO' },
  { code: '+389', country: 'Macedonia', flag: 'MK' },
  { code: '+261', country: 'Madagascar', flag: 'MG' },
  { code: '+265', country: 'Malawi', flag: 'MW' },
  { code: '+60', country: 'Malaysia', flag: 'MY' },
  { code: '+960', country: 'Maldives', flag: 'MV' },
  { code: '+223', country: 'Mali', flag: 'ML' },
  { code: '+356', country: 'Malta', flag: 'MT' },
  { code: '+692', country: 'Marshall Islands', flag: 'MH' },
  { code: '+596', country: 'Martinique', flag: 'MQ' },
  { code: '+222', country: 'Mauritania', flag: 'MR' },
  { code: '+230', country: 'Mauritius', flag: 'MU' },
  { code: '+262', country: 'Mayotte', flag: 'YT' },
  { code: '+52', country: 'Mexico', flag: 'MX' },
  { code: '+691', country: 'Micronesia', flag: 'FM' },
  { code: '+373', country: 'Moldova', flag: 'MD' },
  { code: '+377', country: 'Monaco', flag: 'MC' },
  { code: '+976', country: 'Mongolia', flag: 'MN' },
  { code: '+382', country: 'Montenegro', flag: 'ME' },
  { code: '+212', country: 'Morocco', flag: 'MA' },
  { code: '+258', country: 'Mozambique', flag: 'MZ' },
  { code: '+95', country: 'Myanmar', flag: 'MM' },
  { code: '+264', country: 'Namibia', flag: 'NA' },
  { code: '+674', country: 'Nauru', flag: 'NR' },
  { code: '+977', country: 'Nepal', flag: 'NP' },
  { code: '+31', country: 'Netherlands', flag: 'NL' },
  { code: '+687', country: 'New Caledonia', flag: 'NC' },
  { code: '+64', country: 'New Zealand', flag: 'NZ' },
  { code: '+505', country: 'Nicaragua', flag: 'NI' },
  { code: '+227', country: 'Niger', flag: 'NE' },
  { code: '+234', country: 'Nigeria', flag: 'NG' },
  { code: '+683', country: 'Niue', flag: 'NU' },
  { code: '+672', country: 'Norfolk Island', flag: 'NF' },
  { code: '+1670', country: 'Northern Mariana Islands', flag: 'MP' },
  { code: '+47', country: 'Norway', flag: 'NO' },
  { code: '+968', country: 'Oman', flag: 'OM' },
  { code: '+92', country: 'Pakistan', flag: 'PK' },
  { code: '+680', country: 'Palau', flag: 'PW' },
  { code: '+1878', country: 'Palestine', flag: 'PS' },
  { code: '+507', country: 'Panama', flag: 'PA' },
  { code: '+675', country: 'Papua New Guinea', flag: 'PG' },
  { code: '+595', country: 'Paraguay', flag: 'PY' },
  { code: '+51', country: 'Peru', flag: 'PE' },
  { code: '+63', country: 'Philippines', flag: 'PH' },
  { code: '+64', country: 'Pitcairn', flag: 'PN' },
  { code: '+48', country: 'Poland', flag: 'PL' },
  { code: '+351', country: 'Portugal', flag: 'PT' },
  { code: '+1787', country: 'Puerto Rico', flag: 'PR' },
  { code: '+974', country: 'Qatar', flag: 'QA' },
  { code: '+262', country: 'Reunion', flag: 'RE' },
  { code: '+40', country: 'Romania', flag: 'RO' },
  { code: '+7', country: 'Russia', flag: 'RU' },
  { code: '+250', country: 'Rwanda', flag: 'RW' },
  { code: '+590', country: 'Saint Barthélemy', flag: 'BL' },
  { code: '+290', country: 'Saint Helena', flag: 'SH' },
  { code: '+1869', country: 'Saint Kitts and Nevis', flag: 'KN' },
  { code: '+1758', country: 'Saint Lucia', flag: 'LC' },
  { code: '+590', country: 'Saint Martin', flag: 'MF' },
  { code: '+508', country: 'Saint Pierre and Miquelon', flag: 'PM' },
  { code: '+1784', country: 'Saint Vincent and the Grenadines', flag: 'VC' },
  { code: '+685', country: 'Samoa', flag: 'WS' },
  { code: '+378', country: 'San Marino', flag: 'SM' },
  { code: '+239', country: 'São Tomé and Príncipe', flag: 'ST' },
  { code: '+966', country: 'Saudi Arabia', flag: 'SA' },
  { code: '+221', country: 'Senegal', flag: 'SN' },
  { code: '+381', country: 'Serbia', flag: 'RS' },
  { code: '+248', country: 'Seychelles', flag: 'SC' },
  { code: '+232', country: 'Sierra Leone', flag: 'SL' },
  { code: '+65', country: 'Singapore', flag: 'SG' },
  { code: '+1721', country: 'Sint Maarten', flag: 'SX' },
  { code: '+421', country: 'Slovakia', flag: 'SK' },
  { code: '+386', country: 'Slovenia', flag: 'SI' },
  { code: '+677', country: 'Solomon Islands', flag: 'SB' },
  { code: '+252', country: 'Somalia', flag: 'SO' },
  { code: '+27', country: 'South Africa', flag: 'ZA' },
  { code: '+34', country: 'Spain', flag: 'ES' },
  { code: '+94', country: 'Sri Lanka', flag: 'LK' },
  { code: '+249', country: 'Sudan', flag: 'SD' },
  { code: '+597', country: 'Suriname', flag: 'SR' },
  { code: '+4779', country: 'Svalbard and Jan Mayen', flag: 'SJ' },
  { code: '+268', country: 'Eswatini', flag: 'SZ' },
  { code: '+46', country: 'Sweden', flag: 'SE' },
  { code: '+41', country: 'Switzerland', flag: 'CH' },
  { code: '+963', country: 'Syria', flag: 'SY' },
  { code: '+886', country: 'Taiwan', flag: 'TW' },
  { code: '+992', country: 'Tajikistan', flag: 'TJ' },
  { code: '+255', country: 'Tanzania', flag: 'TZ' },
  { code: '+66', country: 'Thailand', flag: 'TH' },
  { code: '+670', country: 'Timor-Leste', flag: 'TL' },
  { code: '+228', country: 'Togo', flag: 'TG' },
  { code: '+690', country: 'Tokelau', flag: 'TK' },
  { code: '+676', country: 'Tonga', flag: 'TO' },
  { code: '+1868', country: 'Trinidad and Tobago', flag: 'TT' },
  { code: '+216', country: 'Tunisia', flag: 'TN' },
  { code: '+90', country: 'Turkey', flag: 'TR' },
  { code: '+993', country: 'Turkmenistan', flag: 'TM' },
  { code: '+1649', country: 'Turks and Caicos Islands', flag: 'TC' },
  { code: '+688', country: 'Tuvalu', flag: 'TV' },
  { code: '+256', country: 'Uganda', flag: 'UG' },
  { code: '+380', country: 'Ukraine', flag: 'UA' },
  { code: '+971', country: 'United Arab Emirates', flag: 'AE' },
  { code: '+44', country: 'United Kingdom', flag: 'GB' },
  { code: '+1', country: 'United States', flag: 'US' },
  { code: '+1340', country: 'United States Virgin Islands', flag: 'VI' },
  { code: '+598', country: 'Uruguay', flag: 'UY' },
  { code: '+998', country: 'Uzbekistan', flag: 'UZ' },
  { code: '+678', country: 'Vanuatu', flag: 'VU' },
  { code: '+379', country: 'Vatican City', flag: 'VA' },
  { code: '+58', country: 'Venezuela', flag: 'VE' },
  { code: '+84', country: 'Vietnam', flag: 'VN' },
  { code: '+681', country: 'Wallis and Futuna', flag: 'WF' },
  { code: '+212', country: 'Western Sahara', flag: 'EH' },
  { code: '+967', country: 'Yemen', flag: 'YE' },
  { code: '+260', country: 'Zambia', flag: 'ZM' },
  { code: '+263', country: 'Zimbabwe', flag: 'ZW' },
];
